# Site settings
author: Noelle Rolwes
title: 
header-img: img/home-bg.png
email: nrolwes@gmail.com
copyright_name: Noelle Rolwes
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  no0ro

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
